version: "3"
services:
  web:
    build: ./web
    ports:
      - 3000:80
    depends_on:
      - api
  api:
    build: ./api
    environment:
      - PORT=5000
      - DB=mongodb://db:27017/todos
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
